//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efattempt1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Studenter
    {
        private string firstName;
        private string lastName;
        private int nextid;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Studenter()
        {
            this.Betygs = new HashSet<Betyg>();
        }

        public Studenter(string firstName, string lastName, int nextid, string personnummer, string klass)
        {
            this.firstName = firstName;
            this.lastName = lastName;
            this.nextid = nextid;
            Personnummer = personnummer;
            Klass = klass;
        }

        [Key]
        public int StudentID { get; set; }
        public string Förnamn { get; set; }
        public string Efternamn { get; set; }
        public string Personnummer { get; set; }
        public string Klass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Betyg> Betygs { get; set; }
    }
}
